name: userlist_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  async: ^2.12.0
  auto_route: ^7.3.2
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_i18n: ^0.36.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4  
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  injectable: ^2.5.0
  very_good_analysis: ^7.0.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/     
    - assets/locales/
